### ISSUE TITLE
Input Files Missing

### ISSUE THREAD

**Issue by DaminiNanaware** [pritishyuvraj/ShortTextSimilarity#1]
u.pickle and v.pickle missing from lsaWordSim.py

**Comment by pritishyuvraj** [comment]
Hello Damini, 

Unfortunately, I am not maintaining the repo for over a year now. It was my Senior year Engineering Project. I would encourage you to use SVD (https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.svd.html) to generate your own U and V matrices and store them in u.pickle and v.pickle

Feel free to ask more questions. I will try and reply if I recollect stuff.
